
services:

  backend:
    build: ./backend
    container_name: ai-news-backend
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: ai-news-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
